name: python-focus-stack
version: git
summary: Focus Stacking Application
description: |
  An Image Focus Stacking GUI written in python3 / pyqt5

grade: devel
base: core18
confinement: devmode

icon: snap/gui/pyqt-image-focus-stack.png

architectures:
  - build-on: [amd64, arm64, armhf]

# The "extensions: [kde-neon]"" would simplify this yaml a LOT. Unfortunately, PyQt crashes on the "open file" dialog > we have to fallback to old config.
apps:
  python-focus-stack:
    command: desktop-launch  $SNAP/bin/python-focus-stack
    environment:
      DISABLE_WAYLAND: 1
      # Use GTK3 cursor theme, icon theme and open/save file dialogs.
      QT_QPA_PLATFORMTHEME: gtk3
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - opengl
      - home
      - network
      - network-bind
      - network-control
      - mount-observe
      - unity7

parts:
  # This part installs the qt5 dependencies and a `desktop-launch` script to initialise
  # desktop-specific features such as fonts, themes and the XDG environment.
  # 
  # It is copied straight from the snapcraft desktop helpers project. Please periodically
  # check the source for updates and copy the changes.
  #    https://github.com/ubuntu/snapcraft-desktop-helpers/blob/master/snapcraft.yaml
  # 
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
    
  python-focus-stack:
    plugin: python
    python-version: python3
    source: .
    requirements:
      - requirements.txt
    stage-packages:
      - fonts-open-sans
      - python3-cryptography
      - python3-colorlog
      - python3-requests
      - python3-shapely
      - python3-zeroconf
      - python3-distutils
      - python3-pyqt5.qtopengl
      - python3-pyqt5.qtquick
      - python3-pyqt5.qtsvg
      - qml-module-qt-labs-folderlistmodel
      - qml-module-qt-labs-settings
      - qml-module-qtquick-controls
      - qml-module-qtquick-controls2
      - qtwayland5
    after: [desktop-qt5]

# Themes
plugs:
  gsettings:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes:gtk-3-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes:icon-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes:sounds-themes