name: pyqt-image-focus-stack
version: git
summary: PyQt Image Focus Stacking Gui
description: |
 An Image Focus Stacking GUI written in python3/ pyqt5 

grade: devel
base: core18
# for now: devmode go to strict later
confinement: devmode

apps:
  pyqt-image-focus-stack:
    command: desktop-launch $SNAP/bin/QtUi
  #  extensions:
  #    - kde-neon
    plugs:
      - opengl
      - home
      - desktop
      - x11
      - gsettings

parts:
  pyqt-image-focus-stack:
    plugin: python
    source: .
    requirements: 
      - requirements.txt

  qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-depth: 1
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all