name: Build and test [Python, 3.6, 3.7, 3.8, 3.9]

on: [push]

jobs:
  # Build
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Build using python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version:  ${{ matrix.python-version }}
          
      - name: install dependencies [pip]
        run: |
          python -m pip install pip --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -e .
          
      - name: Run linter [flake8]
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 .
      
      - name: Run unit tests [pytest]
        run: |
          pytest
